adaptive_controller:
  ros__parameters:
    controller_node: "/controller_server"

    normal_max_velocity: 0.26
    reduced_max_velocity: 0.18
    stuck_threshold: 3

    normal_goal_tolerance: 0.15
    relaxed_goal_tolerance: 0.30
    goal_struggle_threshold: 8

    normal_inflation_radius: 0.30
    conservative_inflation_radius: 0.40
    bad_efficiency_threshold: 5

    normal_cost_scaling_factor: 3.0
    complex_cost_scaling_factor: 5.0
    complex_environment_threshold: 5

    # move through narrow passages
    narrow_passage_inflation_radius: 0.30
    narrow_passage_cost_scaling_factor: 2.5
    narrow_passage_velocity: 0.20
    narrow_passage_threshold: 3
    narrow_max_theta_velocity: 0.60

    # recovery if robot stops progressing in narrow passage
    narrow_stuck_threshold: 8
    recovery_max_velocity: 0.14
    recovery_min_velocity: 0.00
    recovery_max_theta_velocity: 0.45
    recovery_inflation_radius: 0.30
    recovery_cost_scaling_factor: 2.0